### ISSUE TITLE
questions about _structure_convert

### ISSUE THREAD

**Issue by romain-dartigues** [docker-leash/leash-server#44]
https://github.com/docker-leash/leash-server/blob/d4568b92859c718b7208fd283de9ec4f14a4b7df/docker_leash/checks_list.py#L27-L36

L27: Is it a `@classmethod` or a `@staticmethod` which was desired?

L35-36: There is a return in a loop which will exit at the first iteration; is it expected?
What does happen to the rest of the `data`?

**Comment by kumy** [comment]
@romain-dartigues 

a) Honestly? No idea, I've fixed the code according to the recommendation on codacy...
b) The idea beside it, is to permit write simpler configuration in the yaml files.

From:
```
personnal:
  containersCreate:
    ContainerName: "^foo-.*$"
```

To:
```
personnal:
  containersCreate:
    name: ContainerName
    args: "^foo-.*$"
```
The exit was expected when written, but I admit it's probably not the best way to solve the problem. Currently, all calls come from `checks.add({k: v})` https://github.com/docker-leash/leash-server/blob/d4568b92859c718b7208fd283de9ec4f14a4b7df/docker_leash/config.py#L98-L125, but I'm sure you already found it ;)

**Comment by romain-dartigues** [comment]
a) OK, fixed to `@staticmethod`
b) OK, adding a comment

**Comment by romain-dartigues** [comment]
Covered in PR #45.
