### ISSUE TITLE
Unimplemented routes

### ISSUE THREAD

**Issue by kumy** [docker-leash/leash-server#85]
I think we don't parse such routes: @romain-dartigues would you please add them to your next route parser implementation?

```
INFO[2018-02-24T14:13:19.638788350+01:00] Daemon has completed initialization          
DEBU[2018-02-24T14:13:19.638891265+01:00] Registering routers                          
DEBU[2018-02-24T14:13:19.638903350+01:00] Registering GET, /containers/{name:.*}/checkpoints 
DEBU[2018-02-24T14:13:19.639008480+01:00] Registering POST, /containers/{name:.*}/checkpoints 
DEBU[2018-02-24T14:13:19.639092286+01:00] Registering DELETE, /containers/{name}/checkpoints/{checkpoint} 
```

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:47 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by romain-dartigues** [comment]
Hm, the checkpoints endpoints are [experimental](https://docs.docker.com/engine/reference/commandline/checkpoint/) and does not yet appear in the [API documentation](https://docs.docker.com/engine/api/v1.25/).

Side-note, I do not want to handle rules for "experimental features" in the first `leash` release...

WIP.

**Comment by kumy** [comment]
> Side-note, I do not want to handle rules for "experimental features" in the first leash release...

I finally agree with you :) Let's close for now.
