### ISSUE TITLE
Create a setup.py

### ISSUE THREAD

**Issue by kumy** [docker-leash/leash-server#9]
We should also have the ability to install it via standard python methods

**Comment by romain-dartigues** [comment]
WIP

**Comment by kumy** [comment]
@romain-dartigues dont forget to:
* assign yourself
* move your card in the [project](https://github.com/docker-leash/leash-server/projects/1)

**Comment by romain-dartigues** [comment]
Ready for review, comments and merge.

**Comment by romain-dartigues** [comment]
## Notes

* basic tests can be run with [ʳᵉᶠ](http://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite): `python setup.py test`
* documentation can be generated with [ʳᵉᶠ](http://www.sphinx-doc.org/en/stable/setuptools.html): `python setup.py build_sphinx`
